#!/usr/bin/env node
// gen-aliases.mjs — generate deprecated-OCCT-name aliases for the trimmed V8 build.
//
// OCCT 8.0.0 renamed every NCollection container instantiation to a mangled
// canonical name (TopTools_ListOfShape -> NCollection_List_TopoDS_Shape, etc.).
// The fork's bindgen records the old<->new mapping in the ncollection-manifest's
// `template_typedefs` map. This script reads that map, keeps only the entries whose
// canonical is actually present in *our* trimmed build (read from the generated
// .d.ts), and:
//
//   1. emits a runtime alias map:
//        aliases.generated.json  — { deprecatedName: canonicalMangledName }  (data)
//        aliases.generated.js    — ESM default-export of the same map         (runtime)
//      The wrapper (index.js) applies these onto the module object so that
//      `new oc.TopTools_ListOfShape()` and `instanceof` work for both spellings
//      (same constructor object — no embind re-registration).
//
//   2. BAKES the alias types into the monolithic build .d.ts itself, so the names
//      are present in the single file every consumer / AI reads — not just the
//      package wrapper. It appends `export type <alias> = <canonical>;` and injects
//      `<alias>: typeof <canonical>;` members into the `OpenCascadeInstance` type,
//      so both `let l: TopTools_ListOfShape` and `oc.TopTools_ListOfShape` type-check
//      directly against the raw .d.ts. Idempotent (re-baking strips the prior block).
//
// Usage:
//   node scripts/gen-aliases.mjs --manifest <ncollection-manifest.json> --dts <build.d.ts> --out <dir>

import { readFileSync, writeFileSync } from "node:fs";
import { join, basename } from "node:path";
import { argv, exit } from "node:process";

// --- Supplemental aliases: real OCCT names the bindgen never auto-discovers, that
// map cleanly to a canonical that IS in the build.
//   TopoDS_ListOfShape: real OCCT type (<=7.x docs), == NCollection_List<TopoDS_Shape>
//     (same canonical as the surviving TopTools_ListOfShape deprecated alias).
//   math_Vector: OCCT V8 `using math_Vector = math_VectorBase<double>;` — rejected from
//     template_typedefs (filterTypedef) so it is never auto-surfaced; the canonical
//     math_VectorBase_double IS bound (Workstream A), so surface the friendly name.
const SUPPLEMENTAL_ALIASES = {
  TopoDS_ListOfShape: "NCollection_List_TopoDS_Shape",
  math_Vector: "math_VectorBase_double",
};

const BEGIN = "// ─── BEGIN restored deprecated OCCT names (Workstream B — generated by gen-aliases.mjs) ───";
const END = "// ─── END restored deprecated OCCT names ───";
const MEMBER_TAG = "/* deprecated-name alias */";

function arg(name, def) {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 && i + 1 < argv.length ? argv[i + 1] : def;
}
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const manifestPath = arg("manifest");
const dtsPath = arg("dts");
const outDir = arg("out", ".");

if (!manifestPath || !dtsPath) {
  console.error("usage: gen-aliases.mjs --manifest <m.json> --dts <b.d.ts> --out <dir>");
  exit(2);
}

const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const typedefs = manifest.template_typedefs ?? {};
let dts = readFileSync(dtsPath, "utf8");

// Classes actually declared in the trimmed build's .d.ts == canonicals present at runtime.
const declared = new Set([...dts.matchAll(/^export declare class (\w+)/gm)].map((m) => m[1]));

// Merge manifest typedefs + supplementals, then filter:
//  - canonical must be a real class in this build
//  - alias must NOT already be a real class (never shadow / double-register a name)
const merged = { ...typedefs, ...SUPPLEMENTAL_ALIASES };
const skippedNoCanonical = [];
const aliases = {};
for (const [alias, canonical] of Object.entries(merged)) {
  if (typeof canonical !== "string") continue;
  if (declared.has(alias)) continue;
  if (!declared.has(canonical)) {
    if (alias in SUPPLEMENTAL_ALIASES) skippedNoCanonical.push(`${alias} -> ${canonical}`);
    continue;
  }
  aliases[alias] = canonical;
}
const keys = Object.keys(aliases).sort();
const sorted = Object.fromEntries(keys.map((k) => [k, aliases[k]]));

const provenance =
  `// AUTO-GENERATED by scripts/gen-aliases.mjs — DO NOT EDIT.\n` +
  `// Source: ${basename(manifestPath)} (${manifest.schema ?? "?"}), ` +
  `${keys.length} aliases whose canonical is present in ${basename(dtsPath)}.\n`;

// --- aliases.generated.json (data) ---
writeFileSync(join(outDir, "aliases.generated.json"), JSON.stringify(sorted, null, 2) + "\n");

// --- aliases.generated.js (runtime map consumed by index.js) ---
const jsBody = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(sorted[k])},`).join("\n");
writeFileSync(
  join(outDir, "aliases.generated.js"),
  provenance +
    `// Maps deprecated OCCT type names -> OCCT V8 canonical (mangled) class names.\n` +
    `export default {\n${jsBody}\n};\n`,
);

// --- bake the alias TYPES into the monolithic build .d.ts ---
// 1) strip any previously-baked block + injected members (idempotent re-runs)
dts = dts.replace(new RegExp(`\\n*${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}\\n*`, "g"), "\n");
dts = dts.replace(new RegExp(`\\n  ${escapeRe(MEMBER_TAG)} [^\\n]*`, "g"), "");
// 2) inject `<alias>: typeof <canonical>;` members into the OpenCascadeInstance type
const ocStart = dts.indexOf("export type OpenCascadeInstance = {");
if (ocStart < 0) {
  console.error("gen-aliases: `export type OpenCascadeInstance = {` not found in d.ts");
  exit(1);
}
const ocClose = dts.indexOf("\n};", ocStart);
if (ocClose < 0) {
  console.error("gen-aliases: OpenCascadeInstance closing `};` not found");
  exit(1);
}
const members = keys.map((k) => `\n  ${MEMBER_TAG} ${k}: typeof ${sorted[k]};`).join("");
dts = dts.slice(0, ocClose) + members + dts.slice(ocClose);
// 3) append `export type <alias> = <canonical>;` block at EOF
const typeAliases = keys.map((k) => `export type ${k} = ${sorted[k]};`).join("\n");
dts = dts.replace(/\s*$/, "\n") + `\n${BEGIN}\n${typeAliases}\n${END}\n`;
writeFileSync(dtsPath, dts);

// --- report ---
console.log(`gen-aliases: ${keys.length} aliases -> baked into ${basename(dtsPath)} + aliases.generated.{js,json}`);
const supApplied = Object.keys(SUPPLEMENTAL_ALIASES).filter((k) => k in sorted);
if (supApplied.length) console.log(`  supplemental applied: ${supApplied.join(", ")}`);
if (skippedNoCanonical.length)
  console.log(`  supplemental skipped (canonical absent from build): ${skippedNoCanonical.join(", ")}`);
